- name: install python mininal 
  raw: test -e /usr/bin/python || (apt install -y python-minimal)

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - git

- name: configure ntp server
  template: 
    src: ntp.conf.j2
    dest: "/etc/ntp.conf"

- name: Configure network interface
  command: dhclient

- name: Disable UFW
  command: service ufw stop


