- name: gathering interface macaddress
  set_fact:
    intf_macaddress: "{{ hostvars[inventory_hostname].ansible_eth1.macaddress }}"


- name: populating interface data
  set_fact:
    ctrldatintf_file_content: "DEVICE={{device}}\n\
                               TYPE=Ethernet\n\
                               ONBOOT=yes\n\
                               HWADDR={{ intf_macaddress }}\n\
                               BOOTPROTO=static\n\
                               IPADDR={{ ctrl_data_ip }}\n\
                               PREFIX={{ prefix }}\n\
                               NAME='System eth1'\n\
                               USERCTL=no\n\
                               NM_CONTROLLED=no\n"

- name: creating interface config file
  copy:
    content: "{{ ctrldatintf_file_content }}"
    dest: "/etc/sysconfig/network-scripts/ifcfg-eth1"
    backup: yes
    mode: u=rwx,g=rw,o=rw
